Authorization
iOS-vk-education/2023_2_HealthTechStartUp pull request #4
Opened 2024-02-29 22:07 UTC by MX126

**Добавить**

*  валидацию на текстовые поля в onBoarding
* плавный переход на выходе с профиля
* сохранение фотографии пользователя в storage

**Исправить**

* Переход на другие экраны при открытой клавиатуре
* Всплывающие в терминале ошибке от pin layout

**Продумать**

*Вход в приложение, если есть регистрация от другого способа*

2024-03-02 11:56 UTC, FiX1iN1iT requested changes
Я получше изучил твой код и вот с чем столкнулся:
1. Есть места, где у тебя какая-то математика, и ты всю её вычисляешь в одну строку, из-за чего сложнее понять, что тут происходит. (Пример: SignInViewController, вычисление spacing'а в ф-ции layout())
2. Опять же в layout'е (например, в WelcomeScreenViewController) ты пишешь, что ширина равна x% – думаю, это тоже можно вынести в Constants.
3. Дефолтные значения для unwrapping'а тоже, мне кажется, логичнее вынести в Constants.
4. Некоторые твои вьюхи на SwiftUI очень сложные: нужно поделить на блоки и вынести в отдельные вьюхи так, чтобы конечная вьюха читалась максимально просто (например, если у тебя кастомная с кучей модификаторов, то все эти модификаторы будут лежать во вьюхе с кнопкой, а не в основной вьюхе). Примеры сложных вьюх: ProfileAcknowledgementView, ProfileSetupView.

2024-03-02 11:56 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/SettingsInteractor.swift
> +    weak var viewController: UIViewController?
Зачем интерактору знать про вью контролер?

2024-03-02 11:56 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/SettingsContainer.swift
> +        interactor.viewController = viewController
Зачем?

2024-03-02 11:56 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/SettingsViewController.swift
> +        })
У тебя, вроде, на всех кнопках одна анимация, но ты в каждом вью контролере прописываешь её заново. Может вынести в класс или расширение?

2024-03-02 12:04 UTC, MX126 commented on Everyday/Modules/Settings/SettingsViewController.swift
> +        })
согласен с этим решением,  для кнопок стоит сделать единую анимацию, тут ее даже можно убрать, если запустишь приложение, увидишь, что в модуле настроек просто белая кнопка Выйти, делал для проверки функционала, дальнейшее ее перемещение, окрас и т.п на Ване

2024-03-02 12:13 UTC, MX126 commented on Everyday/Modules/Settings/SettingsInteractor.swift
> +    weak var viewController: UIViewController?
согласен, в этом модуле пока нет необходимости этого делать

2024-03-02 12:24 UTC, MX126 commented
> Я получше изучил твой код и вот с чем столкнулся:
> 
> 1. Есть места, где у тебя какая-то математика, и ты всю её вычисляешь в одну строку, из-за чего сложнее понять, что тут происходит. (Пример: SignInViewController, вычисление spacing'а в ф-ции layout())
> 2. Опять же в layout'е (например, в WelcomeScreenViewController) ты пишешь, что ширина равна x% – думаю, это тоже можно вынести в Constants.
> 3. Дефолтные значения для unwrapping'а тоже, мне кажется, логичнее вынести в Constants.
> 4. Некоторые твои вьюхи на SwiftUI очень сложные: нужно поделить на блоки и вынести в отдельные вьюхи так, чтобы конечная вьюха читалась максимально просто (например, если у тебя кастомная с кучей модификаторов, то все эти модификаторы будут лежать во вьюхе с кнопкой, а не в основной вьюхе). Примеры сложных вьюх: ProfileAcknowledgementView, ProfileSetupView.

1 - я думаю, что в контексте модуля вычисление spacing становится понятным, ввиду "говорящих" компонент, которые там участвуют, если пошагало посмотреть, что происходит, то трудностей с разбором не должно возникнуть

2 - хорошая идея, я так и хотел, но процентные значения обычно рассчитываются относительно размеров родительского элемента в момент выполнения кода, а не как статические значения. Я не могу напрямую сохранить "50%" как статическую константу, потому что размер родителя может быть неизвестен на момент определения константы. Вместо этого, можно только  определить функцию или вычисляемое свойство, которое будет возвращать половину ширины родительского элемента, что того не стоит, как мне кажется

3 - приведи пример пожалуйста, где такое есть, в модулях уже теряюсь)

4 - буду рефакторить

2024-03-02 12:38 UTC, FiX1iN1iT commented
> 1 - я думаю, что в контексте модуля вычисление spacing становится понятным...

Пример:
```swift
let spacing = (((view.frame.width - Constants.Buttons.size.width * 3 - Constants.Buttons.marginHorizontal * 2) / 2) * 100).rounded() / 100
```
Ну такое...
> 2 - хорошая идея, я так и хотел, но ... , что того не стоит, как мне кажется

Да, ты прав.
> 3 - приведи пример пожалуйста, где такое есть, в модулях уже теряюсь)

WelcomeScreenViewController, Keyboard Actions.

2024-03-04 22:11 UTC, whtelie approved these changes

2024-03-05 08:58 UTC, atsed approved these changes

2024-03-05 08:58 UTC, atsed commented on Everyday/Modules/Authorization/SignIn/SignInViewController.swift
> +            let error = NSError(domain: "Everydaytech.ru", code: 400)
Не совсем понял

2024-03-05 08:58 UTC, atsed commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
> +    func login(with userRequest: SignInModel, completion: @escaping(Bool, Error?) -> Void)
Почему Result не используешь?

2024-03-05 21:41 UTC, MX126 commented on Everyday/Modules/Authorization/SignIn/SignInViewController.swift
> +            let error = NSError(domain: "Everydaytech.ru", code: 400)
в дальнейшем буду обрабатывать, было интересно посмотреть на формирование ошибок такого рода

2024-03-05 21:53 UTC, MX126 commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
> +    func login(with userRequest: SignInModel, completion: @escaping(Bool, Error?) -> Void)
SignInPresenter -> handleLoginResult() в нем использую

2024-03-10 22:49 UTC, FiX1iN1iT approved these changes

2024-03-11 11:28 UTC, merged