Auth fixes
iOS-vk-education/2023_2_HealthTechStartUp pull request #6
Opened 2024-03-11 23:14 UTC by MX126

Открываю этот реквест для шлифовки модуля авторизации. 
Протестирайте пожалуйста модуль, скажите, что работает не так, как должно, буду фиксить

2024-03-15 18:34 UTC, FiX1iN1iT requested changes
Отличная работа!

2024-03-15 18:34 UTC, FiX1iN1iT commented on Everyday.xcodeproj/xcuserdata/mk126.xcuserdatad/xcschemes/xcschememanagement.plist
Так и не добавил этот файл в `.gitignore`?

2024-03-15 18:34 UTC, FiX1iN1iT commented on Everyday/Extensions/View+Extension.swift
> +#if canImport(UIKit)
Убери.

2024-03-15 18:34 UTC, FiX1iN1iT commented on Everyday/Services/Auth/GoogleAuth/GoogleAuthService.swift
> +            if let profilePicUrl = user.profile?.imageURL(withDimension: 320) {
Капец... Константу не вынес...

2024-03-15 18:34 UTC, FiX1iN1iT commented on Everyday/Services/Storage/StorageService.swift
> +        try await userReference(userId: userId).child(path).data(maxSize: 3 * 1024 * 1024)
Опять константы...

2024-03-20 20:46 UTC, whtelie approved these changes
если отменить регистрацию по гугл будет ошибка, а по вк нет

2024-03-21 12:02 UTC, FiX1iN1iT approved these changes

2024-03-21 12:06 UTC, MX126 commented on Everyday.xcodeproj/xcuserdata/mk126.xcuserdatad/xcschemes/xcschememanagement.plist
исправил

2024-03-21 16:16 UTC, atsed approved these changes

2024-03-21 16:16 UTC, atsed commented on Everyday/Modules/Authorization/SignIn/SignInPresenter.swift
> +        if CoreDataService.shared.isItemExists(for: service) {
Можно условия убрать

2024-03-21 16:16 UTC, atsed commented on Everyday/Modules/Authorization/SignIn/SignInPresenter.swift
> +        if CoreDataService.shared.isItemExists(for: service) {
Я бы подумал над DI. И взаимодействие с кордатой - это ответственность интерактора

2024-03-21 16:16 UTC, atsed commented on Everyday/Modules/Authorization/SignUp/SignUpPresenter.swift
> +        if CoreDataService.shared.isItemExists(for: service) {
Аналогичная ситуация

2024-03-21 16:16 UTC, atsed commented on Everyday/Modules/Authorization/SignUp/SignUpPresenter.swift
> +        let message = NSMutableAttributedString(string: "AlertManager_signedUp_message".localized)
Почему NSMutableAttributedString?

2024-03-21 16:16 UTC, atsed commented on Everyday/Modules/ScreenSaver/SplashPresenter.swift
> +struct SplashText {
Я бы вынес это из презентера и логику с рандомом сюда закинул

2024-03-21 16:16 UTC, atsed commented on Everyday/Services/Auth/Helpers/CoreData/UserAuthentication+CoreDataClass.swift
> +public class UserAuthentication: NSManagedObject {
Final

2024-03-21 16:16 UTC, atsed commented on Everyday/Services/Auth/Helpers/KeychainService.swift
> +class KeychainService {
Final

2024-03-23 11:45 UTC, MX126 commented on Everyday/Modules/Authorization/SignUp/SignUpPresenter.swift
> +        let message = NSMutableAttributedString(string: "AlertManager_signedUp_message".localized)
исправил

2024-03-23 11:46 UTC, MX126 commented on Everyday/Modules/ScreenSaver/SplashPresenter.swift
> +struct SplashText {
вынести в файлик отдельный ?

2024-03-23 20:35 UTC, merged