Settings
iOS-vk-education/2023_2_HealthTechStartUp pull request #7
Opened 2024-03-25 09:44 UTC by whtelie

Буду исправлять:
- UserDefaults
- Alert`ы
-  Сразу после входа/регистрации не работают переходы, пока не перезайдешь 
- ViewModels через ViewInput в вьюхах с таблицами

2024-04-08 09:51 UTC, FiX1iN1iT requested changes
Отличная работа! Выделил общие проблемы:
1. Непостоянство кодстайла.
2. Непонятно, что должно работать, а что нет: было бы здорово, если бы ты написал в комментарии к pr'у, что, например, ячейки последних 2-ух секций не работают и т.д.
3. Ячейки первой секции, в которые можно переходить одинаковые – отличается только текст, надо переиспользовать один viewController и прокидывать туда разные данные. Скорее всего там есть ещё места, где можно переиспользовать – подумай.
4. В pr'е не должно быть принтов и комментариев.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Support/SceneDelegate.swift
> +        setTheme()
Такого быть не должно, надо создать Сервис подобно тем, что лежат в папке `Services`.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/UserDefaults/UserDefaultsServiceFoerSettings.swift
Всё это надо засунуть в Сервис, который работает с `UserDefaults`

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
>  //            completion(error)
Это, я так понял, не твоё, но комментов в pr'е быть не должно.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
> +            completion(false, NSError(domain: "FirebaseAuthService", code: 0, userInfo: [NSLocalizedDescriptionKey: "UID пользователя не найден"]), nil)
Нам нужно создать свой тип, который будет наследоваться от `Error`.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
> +    }
Эта ф-ция не может закончиться успехом?

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
> +            if let error = error {
Когда ты проверяешь на ошибку, логичнее использовать `guard`, а не `if`.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
> +    }
Эта ф-ция не может закончиться успехом?

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
> +    func deleteAccount(with model: DeleteAccountModel, completion: @escaping (Bool, Error?) -> Void) {
Вместо простого кортежа стоит использовать тип `Result`.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
> +        let db = Firestore.firestore()
В каждой ф-ции есть эта переменная – её надо вынести в приватное св-тво класса.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
> +        let reference = db.collection("user").document(userUID)
"user" в константы.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
> +            "nickname": username
"nickname" в константы.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/Auth/FirebaseAuth/FIrebaseAuthService.swift
> +import Firebase
Насколько я понимаю, тут ты подключаешь всё, что есть в `Firebase` – сомневаюсь, что тебе столько нужно. А если и нужно, то надо удалить встроенные `FirebaseAuth` и `FirebaseFirestore`.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Services/Auth/AuthService.swift
> +            } else if let error = error {
Сначала всегда делается проверка на ошибку.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Units/UnitsViewController.swift
> +    // MARK: - Constants
Странный отступ.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Units/UnitsViewController.swift
> +        if section == 3 {
Стоит вынести индексы в константы и обращаться к ним по имени, чтобы было понятно, для чего секция предназначена.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Units/UnitsViewController.swift
> +        cell.backgroundColor = Constants.gray.withAlphaComponent(Constants.TableView.colorOpacity)
Можно вынести в константы цвет вместе с прозрачностью.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Units/UnitsViewController.swift
> +        return Constants.TableView.numberOfSectionsInTableView
Тут есть return, ниже – нет. Надо быть постоянным в кодстайле.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Units/UnitsViewController.swift
> +            output.getBack()
Нехорошее название ф-ции. `ViewController` не должен знать, что произойдет по нажатию. Хорошее название ф-ции: `output.didSwipe()` – отражает событие, а не результат.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Units/UnitsViewController.swift
> +        override func viewDidLayoutSubviews() {
1. Правильнее вызывать `viewWillLayoutSubviews()`, так как твоя `self.view` дефолтная, следовательно тебе не надо дожидаться, пока на ней что-то появится.
2. Ты не вызвал `super.viewDidLayoutSubviews()`

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Units/UnitsViewController.swift
> +            let swipeRight = UISwipeGestureRecognizer(target: self, action: #selector(swipeFunc(gesture:)))
1. `let swipeRightGestureRecognizer`
2. По-моему, параметр `(gesture:)` можно не писать в этом случае.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Units/UnitsViewController.swift
Делай `Ctrl+I` почаще :)

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Units/Models/UnitsViewModel.swift
`private(set) let` у св-тв структуры.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Theme/ThemeViewController.swift
> +                setLightTheme()
Плохо.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Settings/SettingsViewController.swift
> +        let tyInFooterLabel = UILabel()
Не очень хорошее название переменной.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Settings/SettingsViewController.swift
> +        }
Как будто можно сделать без `if`, если во `viewModel` будет массив.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Settings/SettingsViewController.swift
> +    }
Плохо.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Settings/SettingsViewController.swift
> +        tableView.reloadData()
Зачем?

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Profile/ProfileInteractor.swift
> +        }
Это уже `completion`, и он `escaping`. Тебе не надо возвращать `completion`, достаточно сделать `return`.

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/DeleteAccount/DeleteAccountViewController.swift
> +        default: AlertManager.showInvalidPasswordAlert(on: self, message: message)
Почему `default` – это обязательно `invalidPassword`?

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/DeleteAccount/DeleteAccountRouter.swift
> +        if let sceneDelegate = UIApplication.shared.connectedScenes.first?.delegate as? SceneDelegate {
Что-то страшное. Это точно так делается?

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/DateAndTime/DateAndTimeTableViewCell.swift
> +    func configure(with viewModel: NSAttributedString) {
Почему `viewModel` типа `NSAttributedString`?

2024-04-08 09:51 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/ChangeEmail/ChangeEmailPresenter.swift
> +//        static let invalidPassword: String = "Invalid password"
Удалить.

2024-04-16 23:07 UTC, MX126 commented
Начинаю рефакторить твой код, но и укажу моменты, которые мне не нравятся и я хочу, чтобы ты этим уже занялся сам.

***папка Settings модуля Settings:***
1) SettingsViewModel:
  непонятная каша, которую трудно читать, пришлось разделять по одинаковому типу данных и выравнивать, чтобы получилось красивее. Непонятно, зачем для трех типов ячеек ты делаешь их массивом, если там передается одна моделька, а не несколько, это тоже убрал.
* Я бы разбил это на несколько файлов для каждой viewModel секции таблицы

2) SettingsTableViewCell
подправил функциональные моменты, выглядит красиво

3) SettingsViewController
тут вообще песня... в местах не хватает MARK, теряешься в коде, а функции перегружены в том плане, что код надо было вынести в отдельные функции. Попробовал упростить, получилось получше



***Какие выводы:***
- НЕ пишем огромные функции, выносим код, если видно, что много логики
- Разграничиваем код, чтобы он выглядел аккуратно и его могли читать другие члены команды

2024-05-06 20:37 UTC, MX126 approved these changes

2024-05-06 20:38 UTC, FiX1iN1iT approved these changes

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Authorization/OnBoarding/ProfileAcknowledgement/ProfileAcknowledgementModel.swift
> +    func update(firstname: String? = nil, lastname: String? = nil, nickname: String? = nil, email: String? = nil,
Давай соберем всю эту штуку в структуру. Для String напишем расширение, чтобы тут не было столько if, метод updateVelue например

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Notepad/NotepadScene/Helpers/UIHelper.swift
> +    static func createSevenColumnFlowLayout(in view: UIView) -> UICollectionViewFlowLayout {
Можно объединить с первым методом, куда передаем значение и по дефолту его поставим 1

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Notepad/NotepadScene/Models/NotepadEmptyStateViewViewModel.swift
> +        let titleLabelTitle = "Chilling..."
У вас разве нет файла локализации?

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Notepad/NotepadScene/NotepadEmptyStateView.swift
> +    func configure() {
Обычно это открытый метод с передачей модели

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Notepad/NotepadScene/NotepadInnerCollectionViewCell.swift
> +    private var stackView = UIStackView()
Почему var везде?

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Notepad/NotepadScene/NotepadInnerCollectionViewCell.swift
> +        addSubview(stackView)
На contentView вешать нужно

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Notepad/NotepadScene/NotepadOuterCollectionViewCell.swift
> +    private var innerCollectionView = UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewLayout())
Почему var?

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Notepad/NotepadScene/NotepadViewController.swift
> +    private var outerCollectionView = UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewLayout())
Почему var?

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/ChangeEmail/ChangeEmailViewController.swift
> +    let navBarTitle = UILabel()
private?

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/ChangeLanguage/ChangeLanguagePresenter.swift
> +        //        let locale = Locale(identifier: Constants.enKey)
Коммент

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/ChangeLanguage/ChangeLanguageViewController.swift
> +    override func viewWillLayoutSubviews() {
Почему в этом методе?

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/ChangeLanguage/ChangeLanguageViewController.swift
> +            output.didTapEnCell()
Спорное решение. Не крит

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/ChangeLanguage/ChangeLanguageViewController.swift
> +
Пробел

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/ChangePassword/ChangePasswordViewController.swift
> +    let navBarTitle = UILabel()
private?

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/ChangePassword/ChangePasswordViewController.swift
> +                gestureRecognizer.cancelsTouchesInView = false
Выравнивание

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/DeleteAccount/DeleteAccountViewController.swift
> +    let navBarTitle = UILabel()
Private?

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/DeleteAccount/DeleteAccountViewController.swift
> +                gestureRecognizer.cancelsTouchesInView = false
выравнивание

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/ForgotPassword/ForgotPasswordViewController.swift
> +    let navBarTitle = UILabel()
Private?

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/Profile/ProfileInteractor.swift
> +    let settingsService: SettingsServiceDescription
private

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/Profile/ProfileTableViewCellWithTextField.swift
> +    let textField = UITextField()
Private

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/Profile/ProfileViewController.swift
> +    private func didTapChangeUserImageButton() {
Можно не писать private

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/Settings/SettingsViewController.swift
> +    func setup() {
Private

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/Settings/SettingsViewController.swift
> +    func setupTableView() {
Private

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/Settings/SettingsViewController.swift
> +    func layout() {
Private

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/Theme/ThemeInteractor.swift
> +final class ThemeInteractor {
Будет нужно?

2024-05-07 04:00 UTC, atsed commented on Everyday/Modules/Settings/Units/UnitsInteractor.swift
> +    let settingsService: SettingsServiceDescription
Private

2024-05-07 04:00 UTC, atsed commented on Everyday/Services/Settings/Helpers/Health/HealthService.swift
> +    let healthStore = HKHealthStore()
Private

2024-05-10 12:19 UTC, FiX1iN1iT commented on Everyday/Modules/Notepad/NotepadScene/Models/NotepadEmptyStateViewViewModel.swift
> +        let titleLabelTitle = "Chilling..."
Пофикшу в своём pr'е.

2024-05-10 12:28 UTC, FiX1iN1iT commented on Everyday/Modules/Notepad/NotepadScene/NotepadEmptyStateView.swift
> +    func configure() {
Пофикшу в своём pr'е.

2024-05-10 12:44 UTC, FiX1iN1iT commented on Everyday/Modules/Notepad/NotepadScene/NotepadInnerCollectionViewCell.swift
> +    private var stackView = UIStackView()
Пофикшу в своём pr'е.

2024-05-10 12:48 UTC, FiX1iN1iT commented on Everyday/Modules/Notepad/NotepadScene/NotepadInnerCollectionViewCell.swift
> +        addSubview(stackView)
Пофикшу в своём pr'е.

2024-05-10 12:54 UTC, FiX1iN1iT commented on Everyday/Modules/Notepad/NotepadScene/NotepadOuterCollectionViewCell.swift
> +    private var innerCollectionView = UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewLayout())
Потому что кастомный layout, который зависит от размера родительской view, следовательно придется переопределять после того, как родительская view загрузится.

2024-05-10 12:55 UTC, FiX1iN1iT commented on Everyday/Modules/Notepad/NotepadScene/NotepadViewController.swift
> +    private var outerCollectionView = UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewLayout())
Потому что кастомный layout, который зависит от размера родительской view, следовательно придется переопределять после того, как родительская view загрузится.

2024-05-10 13:01 UTC, FiX1iN1iT commented on Everyday/Modules/Notepad/NotepadScene/Helpers/UIHelper.swift
> +    static func createSevenColumnFlowLayout(in view: UIView) -> UICollectionViewFlowLayout {
Разная реализация – объединить не получится.

2024-05-10 15:02 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/ChangeLanguage/ChangeLanguageViewController.swift
> +    override func viewWillLayoutSubviews() {
Мой косяк)
@whtelie, верни в `viewDidLayoutSubviews()`

2024-05-13 00:40 UTC, atsed approved these changes

2024-05-13 11:04 UTC, merged