New auth
iOS-vk-education/2023_2_HealthTechStartUp pull request #9
Opened 2024-04-29 21:27 UTC by MX126

Изменена бизнес-логика приложения
+ ускорен запуск приложения
Оптимизировал кучу моментов по приле, доработал ошибки и запросы в сеть

В этом pr добью слияние с сущностями Саши( жду от тебя обратной связи что и в каком кол-ве добавлять)
+ на будущее исправил бы позиционирование кнопки при авторизации по почте(пока на это времени нет)

2024-05-03 09:49 UTC, FiX1iN1iT requested changes
Хорошая работа!
1. Видел комменты и print'ы – надо убрать.
2. Не постоянный кодстайл (например, разные отступы между строками) и структуры viper модулей (по-разному обрабатываются схожие события (нажатия на кнопки, закрытие viewController'ов и т. д.)) – можно забить, так как мало времени.

2024-05-03 09:49 UTC, FiX1iN1iT commented on .swiftlint.yml
> +    warning: 160
Не хорошо получилось.

2024-05-03 09:49 UTC, FiX1iN1iT commented on Everyday.xcodeproj/project.xcworkspace/xcuserdata/mk126.xcuserdatad/UserInterfaceState.xcuserstate
Удали из кэша гита этот файл.

2024-05-03 09:49 UTC, FiX1iN1iT commented on Everyday/Entities/Email.swift
> +struct Email {
Не очень название структуры.

2024-05-03 09:49 UTC, FiX1iN1iT commented on Everyday/Entities/Email.swift
> +struct Email {
Не очень название структуры.

2024-05-03 09:49 UTC, FiX1iN1iT commented on Everyday/Modules/Authorization/Authorization/AuthorizationViewController.swift
> +        animateButton(with: signWithGoogleButton)
Думаю, этот метод должен быть вызван из presenter'а.

2024-05-03 09:49 UTC, FiX1iN1iT commented on Everyday/Modules/Authorization/EmailAuth/ForgotPassword/ForgotPasswordViewController.swift
> +        self.dismiss(animated: true, completion: nil)
Это должно происходить в router'е.

2024-05-03 09:49 UTC, FiX1iN1iT commented on Everyday/Modules/Authorization/EmailAuth/SignIn/SignInViewController.swift
> +        togglePasswordButton.frame = CGRect(x: 0, y: 0,
Думаю, координаты (даже (0, 0)) стоит вынести в константы.

2024-05-03 09:49 UTC, FiX1iN1iT commented on Everyday/Modules/Authorization/EmailAuth/SignIn/SignInViewController.swift
> +    @objc func didTapCloseButton() {
Почему до этого `private`, а тут – нет?

2024-05-03 09:49 UTC, FiX1iN1iT commented on Everyday/Modules/Authorization/EmailAuth/SignUp/SignUpPresenter.swift
> +        DispatchQueue.main.async {
Норм, что без `weak self`?

2024-05-03 09:49 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Settings/SettingsViewController.swift
> +        logoutButton.setTitle("logout", for: .normal)
`ViewModel`?

2024-05-03 09:49 UTC, FiX1iN1iT commented on Everyday/Modules/Settings/Settings/SettingsViewController.swift
> +                print("ok")
Убрать print'ы.

2024-05-03 10:08 UTC, whtelie commented on Everyday/Modules/Authorization/EmailAuth/SignIn/SignInViewController.swift
> +        togglePasswordButton.frame = CGRect(x: 0, y: 0,
будет ли так же нормально на .zero заменить?

2024-05-03 14:48 UTC, MX126 commented on .swiftlint.yml
> +    warning: 160
сделал, так как swiftlint слишком сильно ругался на длину localized строки, что-нибудь придумаю

2024-05-03 14:49 UTC, MX126 commented on Everyday.xcodeproj/project.xcworkspace/xcuserdata/mk126.xcuserdatad/UserInterfaceState.xcuserstate
окей, странно что попал туда, вроде настраивал

2024-05-03 14:49 UTC, MX126 commented on Everyday/Entities/Email.swift
> +struct Email {
На что лучше заменить ? Так как она используется только при авторизации по почте

2024-05-03 14:50 UTC, MX126 commented on Everyday/Modules/Authorization/Authorization/AuthorizationViewController.swift
> +        animateButton(with: signWithGoogleButton)
здесь чисто анимация, которая отображается юзеру, не думаю, что она должна быть связана с presenter, так как никаких данных там нет

2024-05-03 14:51 UTC, MX126 commented on Everyday/Modules/Authorization/EmailAuth/ForgotPassword/ForgotPasswordViewController.swift
> +        self.dismiss(animated: true, completion: nil)
по поводу ForgotPassword
он не написан на viper, слишком мало функционала для выделения его под отдельный модуль

2024-05-03 14:51 UTC, MX126 commented on Everyday/Modules/Authorization/EmailAuth/SignIn/SignInViewController.swift
> +    @objc func didTapCloseButton() {
потому что забыл)
исправлю

2024-05-03 14:51 UTC, MX126 commented on Everyday/Modules/Authorization/EmailAuth/SignUp/SignUpPresenter.swift
> +        DispatchQueue.main.async {
посмотрю на утечку, если возникнет, добавлю

2024-05-03 14:52 UTC, MX126 commented on Everyday/Modules/Settings/Settings/SettingsViewController.swift
> +        logoutButton.setTitle("logout", for: .normal)
здесь вообще внимания не обращай, сделал только для проверки на выезд рамки с авторизацией при нажатии на кнопку, в pr Вани это все уйдет

2024-05-03 14:52 UTC, MX126 commented on Everyday/Modules/Settings/Settings/SettingsViewController.swift
> +                print("ok")
такая же ситуация для проверки
принты уберу

2024-05-03 21:31 UTC, whtelie commented on Everyday/Modules/Authorization/EmailAuth/ForgotPassword/ForgotPasswordViewController.swift
> +        self.dismiss(animated: true, completion: nil)
так я делал уже ForgotPassword

2024-05-04 17:08 UTC, whtelie approved these changes
У меня есть рабочий модуль ForgotPassword viper можно его воткнуть, не меняется иконка скрытого и показанного пароля

2024-05-05 16:38 UTC, MX126 commented on Everyday/Modules/Authorization/EmailAuth/SignIn/SignInViewController.swift
> +        togglePasswordButton.frame = CGRect(x: 0, y: 0,
уточним у Егора

2024-05-05 16:39 UTC, MX126 commented on Everyday/Modules/Authorization/EmailAuth/ForgotPassword/ForgotPasswordViewController.swift
> +        self.dismiss(animated: true, completion: nil)
решим после слияния твоей ветки

2024-05-05 16:51 UTC, FiX1iN1iT approved these changes
Ставлю апрув.

2024-05-05 16:51 UTC, FiX1iN1iT commented on .gitignore
> +xcuserdata/
?

2024-05-05 16:51 UTC, FiX1iN1iT commented on Everyday/Entities/DTO.swift
> +}
Зря ты без меня это делал: я иначе сделал.

2024-05-07 04:04 UTC, atsed commented on Everyday/Modules/Authorization/EmailAuth/SignIn/SignInViewController.swift
> +        togglePasswordButton.frame = CGRect(x: 0, y: 0,
.zero норм будет

2024-05-07 04:09 UTC, atsed approved these changes

2024-05-07 04:09 UTC, atsed commented on Everyday/Modules/Authorization/EmailAuth/SignUp/SignUpRouter.swift
> +        // signInViewController.modalTransitionStyle = .crossDissolve
Это нужно?

2024-05-07 04:09 UTC, atsed commented on Everyday/Modules/Authorization/EmailAuth/SignUp/SignUpViewController.swift
> +        print(keyboardHeight)
Убрать

2024-05-07 04:09 UTC, atsed commented on Everyday/Modules/Authorization/OnBoarding/ProfileAcknowledgement/ProfileAcknowledgementView.swift
> +                DispatchQueue.main.async {
Из fb многопоточку нужно убрать

2024-05-07 04:09 UTC, atsed commented on Everyday/Modules/Authorization/OnBoarding/ProfileAcknowledgement/ProfileAcknowledgementView.swift
> +                DispatchQueue.main.async {
Из fb многопоточку нужно убрать

2024-05-07 04:09 UTC, atsed commented on Everyday/Services/Alert/AlertService.swift
> +class AlertService {
final

2024-05-07 04:09 UTC, atsed commented on Everyday/Services/Alert/AlertService.swift
> +class AlertViewController: UIViewController {
final

2024-05-08 11:56 UTC, merged